name: SATARK Weekly Historian

on:
  schedule:
    - cron: '0 0 * * 0' # Midnight every Sunday
  workflow_dispatch: # Allows manual button click

jobs:
  report_generation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install pandas requests

      - name: Run The Historian
        env:
          # DB Keys (To Fetch Data)
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          # Email Keys (To Send Alert)
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python weekly_intel.py
